name: Bug Report
description: Report a bug in Mayara Server
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Mayara version or commit ID
      placeholder: "e.g. 0.4.2 or a1b2c3d"
    validations:
      required: true

  - type: dropdown
    id: radar_brand
    attributes:
      label: Radar brand
      options:
        - Navico
        - Furuno
        - Raymarine
        - Garmin
        - Not Applicable
    validations:
      required: true

  - type: input
    id: radar_model
    attributes:
      label: Radar model
      placeholder: "e.g. HALO20+, DRS4DL"

  - type: textarea
    id: pcap
    attributes:
      label: PCAP file
      description: Drag and drop a PCAP capture file here (optional but very helpful for bugs related to issues with interpreting the radar picture and controls that do not work or have an incorrect value.)

  - type: textarea
    id: media
    attributes:
      label: Screenshot or video
      description: Drag and drop a screenshot or screen recording here if relevant.

  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      placeholder: "What happened? What did you expect to happen?"
    validations:
      required: true
